project_id = "iyckvvnecpnldrxqmzta"

[functions.sentiment-aggregator]
verify_jwt = false

[functions.test-ximatar-patterns]
verify_jwt = false

[functions.generate-company-profile]
verify_jwt = false

[functions.analyze-company-profile]
verify_jwt = true

[functions.analyze-cv]
verify_jwt = true
