-- Clean up stale/fake feed items
DELETE FROM feed_items WHERE metadata->>'demo' = 'true';
DELETE FROM feed_items WHERE metadata->>'demo_batch' IS NOT NULL;
DELETE FROM feed_items WHERE feed_type = 'milestone' AND (title ILIKE '%complete%assessment%' OR title ILIKE '%completa%valutazione%') AND user_id IN (SELECT user_id FROM profiles WHERE pillar_scores IS NOT NULL);
DELETE FROM feed_items WHERE body IS NULL OR body = '';
DELETE FROM feed_items WHERE created_at < now() - interval '90 days';

-- Seed external content
INSERT INTO feed_external_content (title, summary, source_name, source_url, content_type, target_archetypes, target_pillars, tags, language, priority) VALUES
('How the Best Leaders Drive Results Without Burning Out', 'Research shows sustainable high performance comes from energy management, not time management. Key strategies for maintaining drive while avoiding burnout.', 'Harvard Business Review', 'https://hbr.org/topic/leadership', 'article', '{lion,wolf,bee,horse}', '{drive}', '{leadership,performance,wellbeing}', 'en', 2),
('The Science of Motivation: What Really Drives Us', 'Daniel Pink''s research reveals that autonomy, mastery, and purpose are the true drivers of human motivation — not carrots and sticks.', 'TED', 'https://www.ted.com/talks/dan_pink_the_puzzle_of_motivation', 'video', '{}', '{drive}', '{motivation,science,psychology}', 'en', 2),
('Come Mantenere Alta la Motivazione nel Lavoro', 'Strategie pratiche per alimentare la tua spinta professionale anche nei momenti difficili.', 'Il Sole 24 Ore', 'https://www.ilsole24ore.com/art/management', 'article', '{}', '{drive}', '{motivazione,carriera,crescita}', 'it', 1),
('Why Data Literacy Is the Most In-Demand Skill of 2026', 'Companies are prioritizing analytical thinking over raw technical skills. How to develop data literacy regardless of your role.', 'Forbes', 'https://www.forbes.com/leadership/', 'article', '{owl,cat,bear}', '{computational_power}', '{data,analytics,skills}', 'en', 2),
('Thinking in Systems: A Primer for Problem Solvers', 'Donella Meadows'' systems thinking framework is more relevant than ever.', 'MIT Sloan Management Review', 'https://sloanreview.mit.edu/', 'article', '{owl,cat}', '{computational_power,knowledge}', '{systems-thinking,strategy,analysis}', 'en', 1),
('The Art of Persuasion Hasn''t Changed in 2,000 Years', 'Aristotle''s framework of ethos, pathos, and logos still defines effective communication.', 'Harvard Business Review', 'https://hbr.org/topic/communication', 'article', '{parrot,dolphin,fox}', '{communication}', '{communication,persuasion,presenting}', 'en', 2),
('Never Split the Difference: Negotiation Secrets', 'Chris Voss shares tactical empathy techniques that transform how you negotiate.', 'MasterClass', 'https://www.masterclass.com/classes/chris-voss-teaches-the-art-of-negotiation', 'video', '{}', '{communication,drive}', '{negotiation,influence,career}', 'en', 1),
('Comunicare con Impatto: Le Tecniche dei Grandi Leader', 'Dalla comunicazione assertiva alla narrazione strategica: come i leader più efficaci usano le parole.', 'Economia & Management', 'https://www.economiamanagement.it/', 'article', '{parrot,dolphin,lion}', '{communication}', '{comunicazione,leadership,impatto}', 'it', 1),
('How to Think Like a Designer', 'Design thinking isn''t just for designers. It''s a problem-solving framework that any professional can use.', 'IDEO', 'https://designthinking.ideo.com/', 'article', '{fox,cat,chameleon}', '{creativity}', '{design-thinking,innovation,problem-solving}', 'en', 2),
('The Unexpected Benefits of Lateral Thinking in Business', 'Edward de Bono''s lateral thinking techniques are being adopted by Fortune 500 companies.', 'Fast Company', 'https://www.fastcompany.com/section/creativity', 'article', '{fox,cat,parrot}', '{creativity,computational_power}', '{creativity,innovation,lateral-thinking}', 'en', 1),
('The Rise of the T-Shaped Professional', 'Deep expertise in one domain combined with broad knowledge across many. Why the most valuable professionals in 2026 are T-shaped.', 'McKinsey Quarterly', 'https://www.mckinsey.com/quarterly', 'article', '{owl,elephant,bear}', '{knowledge}', '{expertise,learning,career-development}', 'en', 2),
('Ultralearning: How to Master Hard Skills Faster', 'Scott Young''s research-backed framework for accelerated learning.', 'TED', 'https://www.ted.com/topics/education', 'video', '{}', '{knowledge,drive}', '{learning,skills,mastery}', 'en', 1),
('Il Futuro del Lavoro: Competenze che Contano nel 2026', 'Quali competenze saranno più richieste? Una guida alle skill del futuro.', 'Corriere della Sera', 'https://www.corriere.it/economia/', 'article', '{}', '{knowledge,computational_power}', '{futuro,competenze,lavoro}', 'it', 2),
('The Skills-Based Hiring Revolution: Why CVs Are Becoming Obsolete', 'Major employers are dropping degree requirements and focusing on demonstrated competencies.', 'Bloomberg', 'https://www.bloomberg.com/opinion', 'article', '{}', '{}', '{hiring,skills,future-of-work}', 'en', 3),
('Why Self-Awareness Is the Most Underrated Leadership Skill', 'New research shows that 95% of people think they are self-aware, but only 10-15% actually are.', 'Harvard Business Review', 'https://hbr.org/topic/self-awareness', 'article', '{}', '{}', '{self-awareness,leadership,growth}', 'en', 2),
('Come l''AI Sta Trasformando il Recruiting in Italia', 'Dalle valutazioni psicometriche all''analisi dei CV: le aziende italiane stanno adottando strumenti di AI.', 'Wired Italia', 'https://www.wired.it/topic/lavoro/', 'article', '{}', '{}', '{AI,recruiting,italia,innovazione}', 'it', 2),
('The Power of Vulnerability in Professional Growth', 'Brené Brown''s research shows that vulnerability isn''t weakness — it''s the birthplace of innovation.', 'TED', 'https://www.ted.com/talks/brene_brown_the_power_of_vulnerability', 'video', '{}', '{communication,drive}', '{vulnerability,growth,authenticity}', 'en', 1),
('Remote Work Is Reshaping How Companies Evaluate Talent', 'With geographic barriers dissolving, behavioral compatibility signals matter more than ever.', 'The Economist', 'https://www.economist.com/business', 'article', '{}', '{}', '{remote-work,hiring,future-of-work}', 'en', 2)
ON CONFLICT DO NOTHING;