// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyckvvnecpnldrxqmzta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5Y2t2dm5lY3BubGRyeHFtenRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0OTMwNjUsImV4cCI6MjA2NzA2OTA2NX0.OJJ4iid8HbUCmUUkaMVObJOG1y4_t1ia1QTpDhKYlqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});